# Generated by Django 5.1.2 on 2024-10-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_comment_auction_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="description",
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name="auction",
            name="img_link",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
